apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}
  template:
    metadata:
      namespace: default
      name: {{ .Chart.Name }}-{{ .Release.Name }}
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}
    spec:
      serviceAccountName: sa-{{ .Chart.Name }}-{{ .Release.Name }}
      containers:
      - image: {{ .Values.image }}
        name: demo
        ports:
        - containerPort: 80
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MESSAGE
            value: {{ .Values.message }}
